[package]
name = "raytracing"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = { version = "0.17.11", features = ["rayon"] }
miette = { version = "7.5.0", features = ["derive", "fancy"] }
owo-colors = "4.2.0"
png = "0.17.16"
rand = "0.9.0"
toml = "0.8.20"
